### ISSUE TITLE
网页版也没法预约

### ISSUE THREAD

**Issue by zfk513** [azhan1998/fork_apple-store-helperForZhMo#3]
无语了，感觉是我的apple ID 有问题
如果能加个日志就好了
然后这个产品列表不知道是不是全面了，这个虽然能监控，但是没有提醒，感觉也没用呢

**Comment by zfk513** [comment]
> 官网的原因，没库存不做解释。源码放在这边了，有需求你可以实现

但是别人能预约，现在短信也不需要了好像

**Comment by azhan1998** [comment]
刚好看到，go语言我也不是很熟悉。确实不要短信了

**Comment by azhan1998** [comment]
或许你可以优化一下 然后艾特我一下：）

**Comment by zfk513** [comment]
> 刚好看到，go语言我也不是很熟悉。确实不要短信了

hh那你可以预约到吗 ，我是网页预约13也约不到啊，这样有软件我也约不到13 pro ……
